### ISSUE TITLE
supplying a different obj file causes an error

### ISSUE THREAD

**Issue by EternaLearner** [mikecokina/puppet-warp#1]
i am currently working on a project where i need to have a puppet warp algorithm that works similarly to the one in photoshop.

but the issue here is that after using the code in the demo on my image and supplying it with the obj file it got an error

i installed the package using
```
pip install puppet-warp
```
then, used the following code to access the demo
```
from pwarp import Demo

# screen width and height are just the width and height of example.png
Demo(obj_path="path/to/obj_file",screen_width=1983, screen_height= 2982, image="path/to/png_file").run()
```
now the resulting error:
```
Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pwarp\demo\demo.py", line 213, in <module>
    Demo().run()
  File "c:\Users\user\AppData\Local\Programs\Python\Python39\Lib\site-packages\pwarp\demo\demo.py", line 101, in __init__
    self.gi, self.g_product = StepOne.compute_g_matrix(self.vertices, self.edges, self.faces)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pwarp\core\arap.py", line 46, in compute_g_matrix
    l_index, r_index = ops.find_ijlr_vertices(edge, faces)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pwarp\core\ops.py", line 36, in find_ijlr_vertices
    neighbour_index = np.where(face[np.where(face != edge[0])] != edge[1])[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```
Note: i noticed that using the normal puppet.obj file will work but once i changed it to a different obj it errored out.

here are the example png and obj files that can help you recreate the error:[![example.png](https://i.stack.imgur.com/X5J89.png)](https://i.stack.imgur.com/X5J89.png)
and [example.obj](https://easyupload.io/6uzi05)

my objective here is to fix the error

**Comment by mikecokina** [comment]
@EternaLearner, thanks for the issue. I'll try to investigate ASAP, most likely during upcoming weekend.

**Comment by mikecokina** [comment]
@EternaLearner , I have some finding regarded the issue. 

1. First of all, I found that you are using invalid form of wavefront object. Well, it is valid form, but not supported by my library. The faces in your object are defined in following way (e. g.) `f 34/34/34 35/35/35 32/32/32`. I assume it is a form `f v1/vt1/vn1 v2/vt2/vn2 v3/vt3/vn3`, where vX defines indices of face, vtX defines indices of texture and finally vnX defines indices of normal vector. Unfortunately, I do not support such form of wavefront files, just simple form like `f v1 v2 v3`, thus just indices of given face.
If you are not able to save file in simple form, then feel free to adjust method ```read_wavefront``` to be able work with more complicated forms of wavefront file.

2. I've opened your example file and I found out, that your triangulation is somehow malformed. Not sure if it will work with the library anyway. In blender it looks like in following image

![tri](https://user-images.githubusercontent.com/23422027/206757519-112822b4-81a7-42b7-a3cf-c20a09fa3c23.png)

I recommend you to use more homogeneous meshes, something like following one

![homogenous](https://user-images.githubusercontent.com/23422027/206757624-a4dd7186-6baa-4366-b89d-982eb4beebb8.png)
 
3. I also found, that I do not support scaling with factor < 1.0. It is already fixed, but you will have to install version from git, instead of PYPI.

4. Make sure your mesh is inside of image/screen when demo is initialized. Otherwise it will crash on first transformation.  I wasn't aware of this issue until now.

**Comment by EternaLearner** [comment]
this obj file was exported straight from Photoshop (also my real file is exported from Photoshop) by simply extruding my image into 3d. where do i get such an extrusion functionality that  makes this required mesh. (just a small reminder the example obj file provided is no where near the complexity of the real obj file the real file contains holes and isnt even circular)

**Comment by mikecokina** [comment]
I updated wavefront reading method to support following forms of face definitions

```
f v1 v2 v3 ....
f v1/vt1 v2/vt2 v3/vt3 ...
f v1/vt1/vn1 v2/vt2/vn2 v3/vt3/vn3 ...
f v1//vn1 v2//vn2 v3//vn3 ...
```

**Comment by EternaLearner** [comment]
i still have the same error even after reinstalling the package from git clone
```
Traceback (most recent call last):
  File "c:\Users\user\Desktop\drawing code project\fakehumandrawbot\puppettest.py", line 32, in <module>
    Demo(obj_path="example.obj",screen_width=1983, screen_height= 2982, image="example.png").run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\puppet_warp-0.1-py3.9.egg\pwarp\demo\demo.py", line 101, in __init__
    self.gi, self.g_product = StepOne.compute_g_matrix(self.vertices, self.edges, self.faces)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\puppet_warp-0.1-py3.9.egg\pwarp\core\arap.py", line 46, in compute_g_matrix
    l_index, r_index = ops.find_ijlr_vertices(edge, faces)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\puppet_warp-0.1-py3.9.egg\pwarp\core\ops.py", line 36, in find_ijlr_vertices
    neighbour_index = np.where(face[np.where(face != edge[0])] != edge[1])[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by mikecokina** [comment]
Use dev branch instead of master.

**Comment by EternaLearner** [comment]
ok it stopped erroring out but now i realize how important it is to have mesh similar to the one you show cased instead of the weird mesh provided by exporting the file from photoshop how do i get this kind of mesh or extrude a png to 3d and have the same mesh.

**Comment by mikecokina** [comment]
Considering as solved.
